  version: '3'

  services:
    mysqldb:
      image: mysql:8.1.0
      container_name: mysqldb
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: skydiving
      ports:
        - "3307:3306"
      volumes:
        - dbdata:/var/lib/mysql
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: pma
      links:
        - mysqldb
      environment:
        PMA_HOST: mysqldb
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
      restart: always
      ports:
        - 8081:80
    backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      ports:
        - '3003:3002'
      depends_on:
        - mysqldb
    frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - '8080:3000'
      depends_on:
        - backend
  volumes:
    dbdata: